### PR TITLE
Bugfix for comtrade world import value

### PR DESCRIPTION
**Pull request by webbyfox**
To do (delete all that do not apply):

 - [x] Change has a jira ticket that has the correct status.
 - [x] Changelog entry added.

### CODE REVIEW

**Comment by webbyfox** [comment]
@depsiatwal I am checking something hence kept this in draft so please dont merge it

**Comment by webbyfox** [comment]
Ready for review

**Review by depsiatwal — COMMENTED** [review]
no tests ?

**Comment by webbyfox** [comment]
@depsiatwal  Just changing flag in ComTrade API for import value for world and UK. Tests are already there with mock data which don't think require changes

**Review by depsiatwal — APPROVED** [review]
LGTM

**Pull request merged**
